name: hackathon_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.0.6
  restart_app: ^1.2.1
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

#having issues, maybe it works on apple? idk i'll fix later
flutter_launcher_icons:
  andriod: "assets/images/mainAppIcon.png"
  ios: true
  image_path: "assets/images/mainAppIcon.png"