import 'package:flutter/cupertino.dart';
import 'package:hackathon_app/Custom%20Widgets/foodItem.dart';

class Food extends StatelessWidget {
  const Food({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(), //nav bar at the top of screen
      child: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(height: 100,),
              FoodItem(food: "Macaroni and Cheese", calories: 300),
              FoodItem(food: "Mashed Potatoes", calories: 150),
              FoodItem(food: "Soup", calories: 100),
              FoodItem(food: "Pizza", calories: 300),
              FoodItem(food: "Salad", calories: 150),
              FoodItem(food: "Sandwich", calories: 350),
              FoodItem(food: "Pasta", calories: 200),
              FoodItem(food: "Burger", calories: 400),
              FoodItem(food: "Taco", calories: 200),
              FoodItem(food: "Sushi", calories: 250),
              FoodItem(food: "Fried Chicken", calories: 250),
              FoodItem(food: "Steak", calories: 400),
              FoodItem(food: "Rice Bowl", calories: 300),
              FoodItem(food: "Burrito", calories: 400),
              FoodItem(food: "Smoothie", calories: 200),
              FoodItem(food: "Pancakes", calories: 250),
              FoodItem(food: "Waffles", calories: 300),
              FoodItem(food: "Ice Cream", calories: 250),
              FoodItem(food: "Cake", calories: 300),
              FoodItem(food: "Cookies", calories: 100),
              FoodItem(food: "Donuts", calories: 250),
              FoodItem(food: "Popcorn", calories: 100),
              FoodItem(food: "Nachos", calories: 300),
              FoodItem(food: "French Fries", calories: 200),
              FoodItem(food: "Hot Dog", calories: 250),
              FoodItem(food: "Muffins", calories: 200),
              FoodItem(food: "Fruit Salad", calories: 100),
              FoodItem(food: "Grilled Cheese", calories: 350),
              FoodItem(food: "Tacos", calories: 200),
              FoodItem(food: "Quesadilla", calories: 300),
              FoodItem(food: "Wrap", calories: 350),
              FoodItem(food: "Bagel", calories: 250),
              FoodItem(food: "Omelette", calories: 300),
              FoodItem(food: "Stir Fry", calories: 300),
              FoodItem(food: "Fish and Chips", calories: 500),
              FoodItem(food: "Sub Sandwich", calories: 400),
              FoodItem(food: "Calzone", calories: 400),
              FoodItem(food: "Cupcake", calories: 200),
              FoodItem(food: "Biscuit", calories: 200),
              FoodItem(food: "Cheese Plate", calories: 400),
              FoodItem(food: "Chili", calories: 300),
              FoodItem(food: "Gyro", calories: 400),
              FoodItem(food: "Dumplings", calories: 250),
              FoodItem(food: "Spring Rolls", calories: 200),
              FoodItem(food: "Lasagna", calories: 350),
              FoodItem(food: "Quiche", calories: 300),
              FoodItem(food: "Ramen", calories: 400),
              FoodItem(food: "Samosa", calories: 200),
              FoodItem(food: "Casserole", calories: 300),
              FoodItem(food: "Meatballs", calories: 250),
              FoodItem(food: "Potato Chips", calories: 150),
              FoodItem(food: "Pretzel", calories: 200),
              FoodItem(food: "Popcorn Chicken", calories: 300),
              FoodItem(food: "Hamburger", calories: 400),
              FoodItem(food: "Fish Tacos", calories: 250),
              FoodItem(food: "Sausage", calories: 300),
              FoodItem(food: "Shawarma", calories: 400),
              FoodItem(food: "Onion Rings", calories: 250),
              FoodItem(food: "Tiramisu", calories: 300),
              FoodItem(food: "Cheesecake", calories: 350),
              FoodItem(food: "Brownies", calories: 200),
              FoodItem(food: "Cinnamon Rolls", calories: 300),
              FoodItem(food: "Pudding", calories: 150),
              FoodItem(food: "Cupcakes", calories: 200),
              FoodItem(food: "Fondue", calories: 400),
              FoodItem(food: "Caramel Apples", calories: 200),
              FoodItem(food: "Fruit Tart", calories: 250),
              FoodItem(food: "Truffles", calories: 50),
              FoodItem(food: "Popsicles", calories: 100),
              FoodItem(food: "Gelato", calories: 250),
              FoodItem(food: "Sherbet", calories: 150),
              FoodItem(food: "Sorbet", calories: 100),
              FoodItem(food: "Granola Bar", calories: 150),
              FoodItem(food: "Trail Mix", calories: 200),
              FoodItem(food: "Protein Bar", calories: 200),
              FoodItem(food: "Energy Drink", calories: 100),
              FoodItem(food: "Smoothie Bowl", calories: 300),
              FoodItem(food: "Milkshake", calories: 400),
              FoodItem(food: "Hot Chocolate", calories: 200),
              FoodItem(food: "Lemonade", calories: 100),
              FoodItem(food: "Iced Tea", calories: 50),
              FoodItem(food: "Juice", calories: 100),
              FoodItem(food: "Water", calories: 0),
              FoodItem(food: "Coffee", calories: 5),
              FoodItem(food: "Tea", calories: 5),
              FoodItem(food: "Soda", calories: 150),
              FoodItem(food: "Beer", calories: 150),
              FoodItem(food: "Wine", calories: 120),
              FoodItem(food: "Cocktail", calories: 250),
              FoodItem(food: "Mocktail", calories: 100),
              FoodItem(food: "Margarita", calories: 300),
              FoodItem(food: "Martini", calories: 250),
              FoodItem(food: "Whiskey", calories: 100),
              FoodItem(food: "Vodka", calories: 100),
              FoodItem(food: "Rum", calories: 100),
              FoodItem(food: "Gin", calories: 100),
              FoodItem(food: "Scotch", calories: 100),
              FoodItem(food: "Brandy", calories: 100),
              FoodItem(food: "Tequila", calories: 100),
              FoodItem(food: "Cognac", calories: 100),
              FoodItem(food: "Absinthe", calories: 150),
              FoodItem(food: "Sake", calories: 100),
              FoodItem(food: "Soju", calories: 50),
              FoodItem(food: "Mead", calories: 150),
              FoodItem(food: "Cider", calories: 150),
              FoodItem(food: "Champagne", calories: 100),
              FoodItem(food: "Sparkling Wine", calories: 100),
              FoodItem(food: "Port Wine", calories: 100),
              FoodItem(food: "Sherry", calories: 100),
              FoodItem(food: "Moscow Mule", calories: 250),
              FoodItem(food: "Bloody Mary", calories: 200),
              FoodItem(food: "Cosmopolitan", calories: 250),
              FoodItem(food: "Daiquiri", calories: 200),
              FoodItem(food: "Long Island Iced Tea", calories: 300),
              SizedBox(height: 100,),
            ],
          ),
        ),
      )
    );
  }
}
