import 'package:flutter/cupertino.dart';
import 'package:hackathon_app/Custom%20Widgets/foodItem.dart';

class Food extends StatelessWidget {
  const Food({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(), //nav bar at the top of screen
<<<<<<< HEAD
      child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            FoodItem(food: "Macaroni and Cheese"),
            FoodItem(food: "Mashed Potatoes")
          ],
=======
      child: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(height: 100,),
              FoodItem(food: "Macaroni and Cheese"),
              FoodItem(food: "Mashed Potatoes"),
              FoodItem(food: "Soup"),
              FoodItem(food: "Pizza"),
              FoodItem(food: "Salad"),
              FoodItem(food: "Sandwich"),
              FoodItem(food: "Pasta"),
              FoodItem(food: "Burger"),
              FoodItem(food: "Taco"),
              FoodItem(food: "Sushi"),
              FoodItem(food: "Fried Chicken"),
              FoodItem(food: "Steak"),
              FoodItem(food: "Rice Bowl"),
              FoodItem(food: "Burrito"),
              FoodItem(food: "Smoothie"),
              FoodItem(food: "Pancakes"),
              FoodItem(food: "Waffles"),
              FoodItem(food: "Ice Cream"),
              FoodItem(food: "Cake"),
              FoodItem(food: "Cookies"),
              FoodItem(food: "Donuts"),
              FoodItem(food: "Popcorn"),
              FoodItem(food: "Nachos"),
              FoodItem(food: "French Fries"),
              FoodItem(food: "Hot Dog"),
              FoodItem(food: "Muffins"),
              FoodItem(food: "Fruit Salad"),
              FoodItem(food: "Grilled Cheese"),
              FoodItem(food: "Tacos"),
              FoodItem(food: "Quesadilla"),
              FoodItem(food: "Wrap"),
              FoodItem(food: "Bagel"),
              FoodItem(food: "Omelette"),
              FoodItem(food: "Stir Fry"),
              FoodItem(food: "Fish and Chips"),
              FoodItem(food: "Sub Sandwich"),
              FoodItem(food: "Calzone"),
              FoodItem(food: "Cupcake"),
              FoodItem(food: "Biscuit"),
              FoodItem(food: "Cheese Plate"),
              FoodItem(food: "Chili"),
              FoodItem(food: "Gyro"),
              FoodItem(food: "Dumplings"),
              FoodItem(food: "Spring Rolls"),
              FoodItem(food: "Lasagna"),
              FoodItem(food: "Quiche"),
              FoodItem(food: "Ramen"),
              FoodItem(food: "Samosa"),
              FoodItem(food: "Casserole"),
              FoodItem(food: "Meatballs"),
              FoodItem(food: "Potato Chips"),
              FoodItem(food: "Pretzel"),
              FoodItem(food: "Popcorn Chicken"),
              FoodItem(food: "Hamburger"),
              FoodItem(food: "Fish Tacos"),
              FoodItem(food: "Sausage"),
              FoodItem(food: "Shawarma"),
              FoodItem(food: "Onion Rings"),
              FoodItem(food: "Tiramisu"),
              FoodItem(food: "Cheesecake"),
              FoodItem(food: "Brownies"),
              FoodItem(food: "Cinnamon Rolls"),
              FoodItem(food: "Pudding"),
              FoodItem(food: "Cupcakes"),
              FoodItem(food: "Fondue"),
              FoodItem(food: "Caramel Apples"),
              FoodItem(food: "Fruit Tart"),
              FoodItem(food: "Truffles"),
              FoodItem(food: "Popsicles"),
              FoodItem(food: "Gelato"),
              FoodItem(food: "Sherbet"),
              FoodItem(food: "Sorbet"),
              FoodItem(food: "Granola Bar"),
              FoodItem(food: "Trail Mix"),
              FoodItem(food: "Protein Bar"),
              FoodItem(food: "Energy Drink"),
              FoodItem(food: "Smoothie Bowl"),
              FoodItem(food: "Milkshake"),
              FoodItem(food: "Hot Chocolate"),
              FoodItem(food: "Lemonade"),
              FoodItem(food: "Iced Tea"),
              FoodItem(food: "Juice"),
              FoodItem(food: "Water"),
              FoodItem(food: "Coffee"),
              FoodItem(food: "Tea"),
              FoodItem(food: "Soda"),
              FoodItem(food: "Beer"),
              FoodItem(food: "Wine"),
              FoodItem(food: "Cocktail"),
              FoodItem(food: "Mocktail"),
              FoodItem(food: "Margarita"),
              FoodItem(food: "Martini"),
              FoodItem(food: "Whiskey"),
              FoodItem(food: "Vodka"),
              FoodItem(food: "Rum"),
              FoodItem(food: "Gin"),
              FoodItem(food: "Scotch"),
              FoodItem(food: "Brandy"),
              FoodItem(food: "Tequila"),
              FoodItem(food: "Cognac"),
              FoodItem(food: "Absinthe"),
              FoodItem(food: "Sake"),
              FoodItem(food: "Soju"),
              FoodItem(food: "Mead"),
              FoodItem(food: "Cider"),
              FoodItem(food: "Champagne"),
              FoodItem(food: "Sparkling Wine"),
              FoodItem(food: "Port Wine"),
              FoodItem(food: "Sherry"),
              FoodItem(food: "Moscow Mule"),
              FoodItem(food: "Bloody Mary"),
              FoodItem(food: "Cosmopolitan"),
              FoodItem(food: "Daiquiri"),
              FoodItem(food: "Long Island Iced Tea"),
              FoodItem(food: "Mojito"),
              FoodItem(food: "Old Fashioned"),
              FoodItem(food: "Piña Colada"),
              FoodItem(food: "Mai Tai"),
              FoodItem(food: "Sangria"),
              FoodItem(food: "Blue Lagoon"),
              FoodItem(food: "Irish Coffee"),
              FoodItem(food: "White Russian"),
              FoodItem(food: "Mimosa"),
              FoodItem(food: "Bellini"),
              FoodItem(food: "Negroni"),
              FoodItem(food: "Whiskey Sour"),
              FoodItem(food: "Manhattan"),
              FoodItem(food: "Martini"),
              FoodItem(food: "Gimlet"),
              FoodItem(food: "Espresso Martini"),
              FoodItem(food: "Cuba Libre"),
              FoodItem(food: "Mint Julep"),
              FoodItem(food: "French 75"),
              FoodItem(food: "Tom Collins"),
              FoodItem(food: "Paloma"),
              FoodItem(food: "Hot Toddy"),
              FoodItem(food: "Singapore Sling"),
              FoodItem(food: "Pisco Sour"),
              FoodItem(food: "Black Russian"),
              FoodItem(food: "Caipirinha"),
              FoodItem(food: "Mai Tai"),
              FoodItem(food: "Sidecar"),
              FoodItem(food: "Gin and Tonic"),
              FoodItem(food: "Piña Colada"),
              FoodItem(food: "Fuzzy Navel"),
              FoodItem(food: "Sex on the Beach"),
              FoodItem(food: "Tequila Sunrise"),
              FoodItem(food: "Planter's Punch"),
              FoodItem(food: "Hurricane"),
              FoodItem(food: "Zombie"),
              FoodItem(food: "Margarita"),
              FoodItem(food: "Bellini"),
              FoodItem(food: "Daiquiri"),
              FoodItem(food: "Mojito"),
              FoodItem(food: "Caipirinha"),
              FoodItem(food: "Pisco Sour"),
              FoodItem(food: "Mai Tai"),
              FoodItem(food: "Piña Colada"),
              FoodItem(food: "Sazerac"),
              FoodItem(food: "Negroni"),
              FoodItem(food: "Bloody Mary"),
              FoodItem(food: "Tom Collins"),
              FoodItem(food: "Martini"),
              FoodItem(food: "Old Fashioned"),
              FoodItem(food: "Manhattan"),
              FoodItem(food: "Gimlet"),
              FoodItem(food: "White Russian"),
              FoodItem(food: "Rum Punch"),
              FoodItem(food: "Blue Hawaii"),
              FoodItem(food: "Cosmopolitan"),
              FoodItem(food: "Long Island Iced Tea"),
              SizedBox(height: 100,),
            ],
          ),
>>>>>>> 1ed3776f46750f2401b4cc542a3a6f07f265a7ea
        ),
    );
  }
}
